services:
    database:
      image: postgres:16-alpine
      container_name: test
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 0000
        POSTGRES_DB: postgres
      restart: unless-stopped

